config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'register', to: 'registrations#new'
  post 'register', to: 'registrations#create'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'password', to: 'passwords#edit'
  patch 'password', to: 'passwords#update'
  get 'password/reset', to: 'password_resets#new'
  post 'password/reset', to: 'password_resets#create'
  get 'password/reset/edit', to: 'password_resets#edit'
  patch 'password/reset/edit', to: 'password_resets#update'

  get 'movies', to: 'movies#popular'
  get 'movies/:id', to: 'movies#detail'
  get 'search', to: 'movies#search'

  get 'profile', to: 'movie_records#index'

  post 'add_movie', to: 'movie_records#create'
  post 'remove_movie', to: 'movie_records#destroy'
  patch 'update_movie', to: 'movie_records#update'

  # Defines the root path route ("/")
  root "movies#popular"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/movie_record.rb
class MovieRecord < ApplicationRecord
  belongs_to :user

  validates :user, presence: true
  validates :movie_id, presence: true
  validates :title, presence: true
  validates_uniqueness_of :user, scope: :movie_id

  # Pagination
  paginates_per 10

  def self.my_movies(filter, order, title)
    movies = MovieRecord.where('user_id = ?', Current.user)

    if title
      movies = movies.where('title LIKE ?', '%' + title + '%')
    end

    if filter == 'watched'
      movies = movies.where('watched = ?', true)
    elsif filter == 'unwatched'
      movies = movies.where('watched = ?', false)
    end

    if order == 'asc'
      movies = movies.order('created_at ASC')
    elsif order == 'desc'
      movies = movies.order('created_at DESC')
    end

    return movies
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :movie_records

  validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "must be a valid email address"}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_user

  def set_current_user
    if session[:user_id]
      Current.user = User.find_by(id: session[:user_id])
    end
  end

  def require_user_logged_in!
    redirect_to login_path, alert: 'You must be logged in to do that' if Current.user.nil?
  end

  def render_404
    raise ActionController::RoutingError.new('Not Found')
  end
end

app/controllers/movie_records_controller.rb
class MovieRecordsController < ApplicationController
  before_action :require_user_logged_in!, only: [:index]

  def create
    @movie_record = MovieRecord.new
    @movie_record.user = Current.user
    @movie_record.movie_id = params[:movie_id]
    @movie_record.title = params[:title]
    @movie_record.image = params[:image]
    @movie_record.watched = false
    if @movie_record.save
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    @movie_record = MovieRecord.find_by(:user => Current.user, :movie_id => params[:movie_id])

    if @movie_record.destroy
      redirect_back(fallback_location: root_path)
    end
  end

  def update
    @movie_record = MovieRecord.find_by(:user => Current.user, :movie_id => params[:movie_id])

    @movie_record.watched = !@movie_record.watched
    if !@movie_record.watched
      @movie_record.watched_date = nil
    end

    if @movie_record.save
      redirect_back(fallback_location: root_path)
    end
  end

  def index
    @filter = params[:filter]
    @order = params[:order]
    @title = params[:title]
    @movie_records = MovieRecord.my_movies(@filter, @order, @title).page params[:page]
  end
end

app/controllers/movies_controller.rb
require 'uri'
require 'erb'
require 'net/http'
require 'json'

class MoviesController < ApplicationController
  def popular
    uri = URI(ENV['apiAddr'] + 'MostPopularMovies/' + ENV['apiKey'])
    res = Net::HTTP::get_response(uri)
    @movies = JSON.parse(res.body)['items'].first(10) if res.is_a?(Net::HTTPSuccess)
  end

  def detail
    uri = URI(ENV['apiAddr'] + 'Title/' + ENV['apiKey'] + '/' + params[:id])
    res = Net::HTTP::get_response(uri)
    @movie = JSON.parse(res.body) if res.is_a?(Net::HTTPSuccess)
    if not @movie['title']
      render_404
    end
    @added = false
    if Current.user
      @added = MovieRecord.exists?(:user => Current.user, :movie_id => @movie['id'])
    end
  end

  def search
    uri = URI(ENV['apiAddr'] + 'SearchMovie/' + ENV["apiKey"] + '/' + ERB::Util.url_encode(params[:search]))
    res = Net::HTTP::get_response(uri)
    @movies = JSON.parse(res.body)['results'].select{ |movie| movie['image'] != '' }.first(10) if res.is_a?(Net::HTTPSuccess)
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:email])

    if @user.present?
      PasswordMailer.with(user: @user).reset.deliver_now
    end

    redirect_to login_path, notice: 'If an account with that email exists, you will receive an email to reset your password'
  end

  def edit
    @user = User.find_signed!(params[:token], purpose: 'password_reset')
  rescue ActiveSupport::MessageVerifier::InvalidSignature
    redirect_to login_path, alert: 'Your token has expired'
  end

  def update
    @user = User.find_signed!(params[:token], purpose: 'password_reset')

    if @user.update(password_params)
      redirect_to login_path, notice: 'Your password was reset successfully'
    else
      render :edit, status: :bad_request
    end
  end

  private

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  before_action :require_user_logged_in!

  def edit
  end

  def update
    if Current.user.update(password_params)
      redirect_to root_path, notice: 'Password changed successfully'
    else
      render :edit, status: :bad_request
    end
  end

  private

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'Successfully created account'
    else
      render :new, status: :bad_request
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: 'Logged in successfully'
    else
      flash[:alert] = 'Invalid email or password'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Logged out'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movie_records_helper.rb
module MovieRecordsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieLog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body style='font-family: Courier New'>
    <% if Current.user %>
      <%= render partial: "shared/navbar_logged_in" %>
    <% else %>
      <%= render partial: "shared/navbar_logged_out" %>
    <% end %>
    <div class="container" align='center' style="padding-top: 5px;">
      <%= render partial: 'shared/flash' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/movie_records/index.html.erb
<!--
<%= link_to 'All', profile_path(filter: 'all', order: @order) %>
<br>
<%= link_to 'Watched', profile_path(filter: 'watched', order: @order) %>
<br>
<%= link_to 'Unwatched', profile_path(filter: 'unwatched', order: @order) %>
<br>
<%= link_to 'Order', profile_path(filter: @filter, order: @order == 'desc' ? 'asc' : 'desc') %>
<br>
<% @movie_records.each do |movie_record| %>
  <%= movie_record.title %><br>
<% end %>
<%= paginate @movie_records %>
-->
<div class='d-inline-flex justify-content-between w-100 py-5'>
  <div class='btn-group'>
    <%= link_to 'Watched', profile_path(filter: 'watched', order: @order, title: @title), class: @filter == 'watched' ? 'btn btn-secondary' : 'btn btn-outline-secondary' %>
    <%= link_to 'All', profile_path(filter: 'all', order: @order, title: @title), class: @filter == 'all' ? 'btn btn-secondary' : 'btn btn-outline-secondary' %>
    <%= link_to 'Not Watched', profile_path(filter: 'unwatched', order: @order, title: @title), class: @filter == 'unwatched' ? 'btn btn-secondary' : 'btn btn-outline-secondary' %>
  </div>
  <div class='d-flex'>
      <%= form_tag profile_path, method: :get, class: 'd-flex' do %>
        <%= search_field_tag :title, params[:title], placeholder: 'Search', class: 'form-control me-2' %>
        <%= hidden_field_tag :filter, @filter %>
        <%= hidden_field_tag :order, @order %>
        <%= submit_tag 'Search', class: 'btn btn-outline-success' %>
      <% end %>
      <div class='me-2'></div>
      <%= link_to 'Clear', profile_path(filter: @filter, order: @order), class: 'btn btn-outline-danger' %>
  </div>
</div>
<table class='table align-middle'>
  <thead>
    <th>
    </th>
    <th>
      Title
    </th>
    <th class='d-flex'>
      Added Date
      <div class='me-2'></div>
      <%= link_to profile_path(filter: @filter, order: @order == 'desc' ? 'asc' : 'desc', title: @title) do %>
        <% if @order == 'desc' %>
          <i class="bi bi-arrow-down-circle"></i>
        <% elsif %>
          <i class="bi bi-arrow-up-circle"></i>
        <% end %>
      <% end %>
    </th>
    <th>
      Watched
    </th>
    <th>
      Remove
    </th>
  </thead>
  <tbody>
    <% @movie_records.each do |movie_record| %>
      <tr>
        <td>
            <img src='<%= movie_record.image %>' class='img-fluid rounded-start' style='width: 50px;' alt='...'>
        </td>
        <td style='width: 50%'>
          <%= link_to movie_record.title, '/movies/' + movie_record.movie_id %>
        </td>
        <td>
          <%= movie_record.created_at.to_date %>
        </td>
        <td>
          <% if movie_record.watched %>
            <%= button_to 'Unwatch', update_movie_path(movie_id: movie_record.movie_id), method: 'patch', class: 'btn btn-outline-danger' %>
          <% else %>
            <%= button_to 'Watch', update_movie_path(movie_id: movie_record.movie_id), method: 'patch', class: 'btn btn-outline-primary' %>
          <% end %>
        </td>
        <td>
          <%= button_to 'Remove', remove_movie_path(movie_id: movie_record.movie_id), method: 'post', class: 'btn btn-outline-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div>
  <%= paginate @movie_records %>
</div>

app/views/movies/detail.html.erb
<div class="card w-90 mt-5 border-0">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="<%= @movie["image"] %>" class="img-fluid rounded-start" alt="...">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <div align='left'>
          <h3 class="card-title mb-5">
            <%= @movie['fullTitle'] %> (<%= @movie['contentRating'] %>)
          </h3>
          <h5 class='card-subtitle mb-4'>
            Director(s): <%= @movie['directors'] %>
          </h5>
          <h5 class='card-subtitle mb-4'>
            Starring: <%= @movie['stars'] %>
          </h5>
          <h5 class='card-subtitle mb-4'>
            Release Date: <%= @movie['releaseDate'] %>
          </h5>
          <h5 class='card-subtitle mb-4'>
            Genres: <%= @movie['genres'] %>
          </h5>
          <h5 class='card-subtitle mb-4'>
            Runtime: <%= @movie['runtimeStr'] %>
          </h5>
          <p class='card-text'>
            <%= @movie['plot'] %>
          </p>
        </div>
        <div style='position: absolute; bottom: 15px; right: 15px;'>
          <% if Current.user %>
            <% if @added %>
              <%= button_to 'Remove from list', remove_movie_path(user_id: Current.user.id, movie_id: @movie['id']), method: 'post', class: 'btn btn-secondary' %>
            <% else %>
              <%= button_to 'Add to list', add_movie_path(user_id: Current.user.id, movie_id: @movie['id'], title: @movie['fullTitle'], image: @movie['image']), method: 'post', class: 'btn btn-secondary' %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/movies/popular.html.erb
<ul>
  <% @movies.each do |movie| %>
    <div class="card w-50 mb-3">
      <div class="row g-0">
        <div class="col-md-4">
          <img src="<%= movie["image"] %>" class="img-fluid rounded-start" alt="...">
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title">
              <%= movie['fullTitle'] %>
            </h5>
            <br>
            <% casts = movie["crew"].split(", ") %>
            <% casts.first(4).each do |cast| %>
              <p class="card-text">
                <%= cast.to_s %>
              </p>
            <% end %>
            <div style='position: absolute; bottom: 10px; right: 10px;' >
              <%= link_to 'View More', '/movies/' + movie['id'], class: 'btn btn-secondary' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</ul>

app/views/movies/search.html.erb
<ul>
  <% @movies.each do |movie| %>
    <div class="card w-50 mb-3">
      <div class="row g-0">
        <div class="col-md-4">
          <img src="<%= movie["image"] %>" class="img-fluid rounded-start" alt="...">
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title">
              <%= movie['title'] %>
            </h5>
            <br>
            <p class="card-text">
              <%= movie['description'] %>
            </p>
            <div style='position: absolute; bottom: 15px; right: 15px;' >
              <%= link_to 'View More', '/movies/' + movie['id'], class: 'btn btn-secondary' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</ul>

app/views/password_resets/edit.html.erb
<h1>Reset your password</h1>

<div align='left'>
  <%= form_with model: @user, url: password_reset_edit_path(token: params[:token]) do |form| %>
    <% if form.object.errors.any? %>
      <div class='alert alert-danger'>
        <% form.object.errors.full_messages.each do |message| %>
          <div><%= message %></div>
        <% end %>
      </div>
    <% end %>

    <div class='mb-3'>
      <%= form.label :password %>
      <%= form.password_field :password, class: 'form-control', placeholder: 'password' %>
    </div>
    <div class='mb-3'>
      <%= form.label :password_confirmation %>
      <%= form.password_field :password_confirmation, class: 'form-control', placeholder: 'password' %>
    </div>

    <div class='mb-3'>
      <%= form.submit 'Reset Password', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/password_resets/new.html.erb
<h1>Forgot your password?</h1>

<div align='left'>
  <%= form_with url: password_reset_path do |form| %>
    <div class='mb-3'>
      <%= form.label :email %>
      <%= form.text_field :email, class: 'form-control', placeholder: 'email@email.com' %>
    </div>

    <div class='mb-3'>
      <%= form.submit 'Reset Password', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class='alert alert-info mt-4' role='alert'>
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class='alert alert-warning mt-4' role='alert'>
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/shared/_navbar_logged_in.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class='nav-item'>
          <%= link_to 'My Movies', profile_path(filter: 'all', order: 'desc'), class: 'nav-link' %>
        </li>
        <div class='px-3'></div>
        <%= form_tag search_path, method: :get, class: 'd-flex' do %>
          <%= search_field_tag :search, params[:search], placeholder: 'Search', :required => 'required', class: 'form-control me-2' %>
          <%= submit_tag 'Search', class: 'btn btn-outline-success' %>
        <% end %>
      </ul>
      <ul class='navbar-nav ms-auto mb-2 mb-lg-0'>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%= Current.user.email %>
          </a>
          <ul class="dropdown-menu dropdown-menu-end">
            <li>
              <%= link_to 'Change Password', password_path, class: 'dropdown-item' %>
            </li>
            <li><hr class="dropdown-divider"></li>
            <li>
              <%= button_to 'Logout', logout_path, method: :delete, class: 'dropdown-item' %>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_navbar_logged_out.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= form_tag search_path, method: :get, class: 'd-flex' do %>
            <%= search_field_tag :search, params[:search], placeholder: 'Search', :required => 'required', class: 'form-control me-2' %>
            <%= submit_tag 'Search', class: 'btn btn-outline-success' %>
          <% end %>
        </li>
      </ul>
      <ul class='navbar-nav ms-auto mb-2 mb-lg-0'>
        <li class='nav-item'>
          <%= link_to 'Register', register_path, class: 'nav-link' %>
        </li>
        <li class='nav-item'>
          <%= link_to 'Login', login_path, class: 'nav-link' %>
        </li>
      </ul>
    </div>
  </div>
</nav>